/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorAlumno;
import ec.edu.ups.controlador.ControladorCurso;
import ec.edu.ups.modelo.Alumno;
import ec.edu.ups.modelo.Curso;
import ec.edu.ups.modelo.Docente;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NANCY
 */
public class VentanaRegistraEstudiante extends javax.swing.JInternalFrame {

    private ControladorCurso controladorCurso;
    private ControladorAlumno controladorAlumno;
    private Docente docente;
    /**
     * Creates new form VentanaRegistraEstudiante
     * @param controladorCurso
     * @param controladorAlumno
     */
    public VentanaRegistraEstudiante(ControladorCurso controladorCurso, ControladorAlumno controladorAlumno) {
        initComponents();
        
        this.controladorCurso=controladorCurso;
        this.controladorAlumno=controladorAlumno;
        docente=Docente.instance;
        
    }
    
    
    public List<Alumno> listaAlumno(){
        List<Alumno> listaAlumnos;
        listaAlumnos = new ArrayList<>();
        for (Alumno alumno : controladorAlumno.getListaGenerica()){
            Curso curso= docente.getCurso();
            Curso curso2= alumno.getCurso();
            System.out.println(curso);
            System.out.println(curso2);
            if(curso.equals(curso2)){
                listaAlumnos.add(alumno);
            }
        }
        return listaAlumnos;
    }
    
    
    public void cargarCodigo() {
        int cod = controladorAlumno.cargarCodigo();
        txtCodigo.setText(String.valueOf(cod));
    }
    
    public void cargarDatos() {
       DefaultTableModel modeloTabla = (DefaultTableModel) tblCurso.getModel();

        modeloTabla.setRowCount(0);
        for (var curso : controladorCurso.getListaGenerica()) {
            Object[] rowData = {curso.getCodigo(), curso.getNombre()};
            modeloTabla.addRow(rowData);
        }
        tblCurso.setModel(modeloTabla);
    }
    public void ListaEstu () {
        DefaultListModel modelo = new DefaultListModel();
        modelo.clear();
        
        for (Alumno alumno : controladorAlumno.getListaGenerica()) {
            modelo.addElement(alumno.getNombreApellido());
        }
        Lista.setModel(modelo);
    }
    
    public void limpiar(){
        txtCedula.setText("");
        txtNombre.setText("");

        txtComportamiento.setText("");
        txtCodigoCurso.setText("");
        txtNombreCurso.setText("");
        txtDatosInformacion.setText("");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtComportamiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoCurso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNombreCurso = new javax.swing.JTextField();
        btnRegistrarAlumno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCurso = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDatosInformacion = new javax.swing.JTextArea();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Alumno ");

        jLabel2.setText("Cedula");

        jLabel3.setText("Nombre y Apellido");

        jLabel5.setText("Codigo");

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setText("Comportamiento");

        txtComportamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComportamientoActionPerformed(evt);
            }
        });

        jLabel7.setText("Codigo Curso");

        txtCodigoCurso.setEditable(false);
        txtCodigoCurso.setBackground(new java.awt.Color(255, 255, 204));

        jLabel8.setText("Curso");

        txtNombreCurso.setEditable(false);
        txtNombreCurso.setBackground(new java.awt.Color(255, 255, 204));

        btnRegistrarAlumno.setText("Registrar Alumno");
        btnRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAlumnoActionPerformed(evt);
            }
        });

        tblCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo Curso", "Nombre Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCursoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCurso);

        jScrollPane2.setViewportView(Lista);

        jButton1.setText("Cargar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtDatosInformacion.setEditable(false);
        txtDatosInformacion.setBackground(new java.awt.Color(255, 255, 204));
        txtDatosInformacion.setColumns(20);
        txtDatosInformacion.setRows(5);
        jScrollPane3.setViewportView(txtDatosInformacion);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(324, 324, 324)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCedula)
                                    .addComponent(txtNombre)
                                    .addComponent(txtComportamiento)
                                    .addComponent(txtCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addComponent(btnRegistrarAlumno))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jButton1)
                                        .addGap(87, 87, 87)
                                        .addComponent(btnEliminar)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane3)))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtComportamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrarAlumno)
                            .addComponent(jButton1)
                            .addComponent(btnEliminar))
                        .addGap(41, 41, 41)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        cargarCodigo();
        cargarDatos();
        ListaEstu();
    }//GEN-LAST:event_formInternalFrameActivated

    private void btnRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAlumnoActionPerformed
        boolean resultado = false;
        int codigo=Integer.parseInt(txtCodigo.getText());
        String cedula= txtCedula.getText();
        String nombre= txtNombre.getText();
        String comportamineto=txtComportamiento.getText();
        String codigoCurso= txtCodigoCurso.getText();
        String nombreCurso= txtNombreCurso.getText();
        
        int codigoc=Integer.parseInt(txtCodigoCurso.getText());
        Curso c = new Curso(codigoc);
        Curso curso=controladorCurso.read(c);
        
        Alumno alum= new Alumno(nombre);

        if(cedula.isEmpty()||nombre.isEmpty()||comportamineto.isEmpty()||codigoCurso.isEmpty()||nombreCurso.isEmpty()){
            JOptionPane.showMessageDialog(this, "Llene todos los campos solicitados");
        }else{
            if(controladorAlumno.read(alum)!= null){
                Alumno alumno = new Alumno(codigo, comportamineto, curso, cedula, nombre);
                resultado =controladorAlumno.update(alumno);
                
            }else{
                Alumno alumno = new Alumno(codigo, comportamineto, curso, cedula, nombre);
                resultado =controladorAlumno.create(alumno);
                
            }
            
            limpiar();
            JOptionPane.showMessageDialog(this, "Operación : " + resultado);
            cargarDatos();
            dispose();
        }
    }//GEN-LAST:event_btnRegistrarAlumnoActionPerformed

    private void tblCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCursoMouseClicked
        int fila = tblCurso.getSelectedRow();
        int cod = (int) tblCurso.getValueAt(fila, 0);
        String nombre = (String) tblCurso.getValueAt(fila, 1);

        txtCodigoCurso.setText(String.valueOf(cod));
        txtNombreCurso.setText(nombre);
    }//GEN-LAST:event_tblCursoMouseClicked

    private void txtComportamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComportamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComportamientoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre= Lista.getSelectedValue();
        Alumno alum= new Alumno(nombre);
        Alumno alumno= controladorAlumno.read(alum);
        
        txtCodigo.setText(String.valueOf(alumno.getCodigo()));
        txtCedula.setText(alumno.getCedula());
        txtNombre.setText(alumno.getNombreApellido());
       
        txtComportamiento.setText(alumno.getComportamiento());
        
        Curso cur= alumno.getCurso();
        txtCodigoCurso.setText(String.valueOf(cur.getCodigo()));
        txtNombreCurso.setText(cur.getNombre());
        
        txtDatosInformacion.setText(alumno.toString());

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int eliminar = JOptionPane.showConfirmDialog(this, "¿Seguro quieres eliminar este Alumno?");
        Alumno alum= new Alumno(txtNombre.getText());
        Alumno alumno= controladorAlumno.read(alum);
        if(eliminar == JOptionPane.YES_OPTION){
            boolean resultado = controladorAlumno.delete(alumno);
            JOptionPane.showMessageDialog(this, "Operación : " + resultado);
            limpiar();
            cargarDatos();
            dispose();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> Lista;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrarAlumno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblCurso;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoCurso;
    private javax.swing.JTextField txtComportamiento;
    private javax.swing.JTextArea txtDatosInformacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreCurso;
    // End of variables declaration//GEN-END:variables

    
}
