/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorActividades;
import ec.edu.ups.controlador.ControladorAlumno;
import ec.edu.ups.controlador.ControladorCurso;
import ec.edu.ups.controlador.ControladorDocente;
import ec.edu.ups.controlador.ControladorRector;
import javax.swing.JMenuItem;

/**
 *
 * @author NANCY
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private VentanaRegistarDocente ventanaRegistarDocente;
    private VentanIniciarSesion ventanaIniciarSesion;
    private VentanaAbrirCurso ventanaAbrirCurso;
    private VentanaRegistraEstudiante ventanaRegistraEstudiante;
    private VentanaGestionActividades ventanaGestionActividades;
    
    private ControladorRector controladorRector;
    private ControladorCurso controCurso;
    private ControladorAlumno controladorAlumno;
    private ControladorDocente controladorDocente;
    private ControladorActividades controladorActividades;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        controladorRector = new ControladorRector();
        controCurso= new ControladorCurso("datos/cursos.obj");
        controladorAlumno= new ControladorAlumno("datos/alumnos.obj");
        controladorDocente= new ControladorDocente("datos/docentes.obj");
        controladorActividades= new ControladorActividades("datos/actividades.obj");
        
        ventanaRegistarDocente= new VentanaRegistarDocente(controCurso,controladorDocente);
        ventanaAbrirCurso= new VentanaAbrirCurso(controCurso);
        ventanaRegistraEstudiante = new VentanaRegistraEstudiante(controCurso,controladorAlumno);
        ventanaGestionActividades = new VentanaGestionActividades(controladorActividades);
        
        ventanaIniciarSesion = new VentanIniciarSesion(controladorRector,this,controladorDocente,ventanaRegistraEstudiante);
        
        
        menuItemAbrirCurso.setVisible(false);
        menuItemCerrarSesion.setVisible(false);

        menuItemRegistrarDocente.setVisible(false);
        menuItemRegistrarAlumno.setVisible(false);
        menuItemCrearActividad.setVisible(false);
        
    }

    public JMenuItem getMenuItemAbrirCurso() {
        return menuItemAbrirCurso;
    }

    public JMenuItem getMenuItemCerrarSesion() {
        return menuItemCerrarSesion;
    }

   

    public JMenuItem getMenuItemIniciarSesion() {
        return menuItemIniciarSesion;
    }

    public JMenuItem getMenuItemRegistrarDocente() {
        return menuItemRegistrarDocente;
    }

    public JMenuItem getMenuItemRegistrarAlumno() {
        return menuItemRegistrarAlumno;
    }

    public JMenuItem getMenuItemCrearActividad() {
        return menuItemCrearActividad;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuItemIniciarSesion = new javax.swing.JMenuItem();
        menuItemAbrirCurso = new javax.swing.JMenuItem();
        menuItemRegistrarAlumno = new javax.swing.JMenuItem();
        menuItemRegistrarDocente = new javax.swing.JMenuItem();
        menuItemCrearActividad = new javax.swing.JMenuItem();
        menuItemCerrarSesion = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        menuItemIniciarSesion.setMnemonic('s');
        menuItemIniciarSesion.setText("Iniciar Sesion");
        menuItemIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIniciarSesionActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemIniciarSesion);

        menuItemAbrirCurso.setText("Abrir Curso");
        menuItemAbrirCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAbrirCursoActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemAbrirCurso);

        menuItemRegistrarAlumno.setText("Registrar Alumno");
        menuItemRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistrarAlumnoActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemRegistrarAlumno);

        menuItemRegistrarDocente.setText("Registrar Docente");
        menuItemRegistrarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistrarDocenteActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemRegistrarDocente);

        menuItemCrearActividad.setText("Gestion Actividad");
        menuItemCrearActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearActividadActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemCrearActividad);

        menuItemCerrarSesion.setMnemonic('a');
        menuItemCerrarSesion.setText("Cerrar Sesion");
        menuItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCerrarSesionActionPerformed(evt);
            }
        });
        fileMenu.add(menuItemCerrarSesion);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuItemIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIniciarSesionActionPerformed
        desktopPane.add(ventanaIniciarSesion);
        ventanaIniciarSesion.setVisible(true);
    }//GEN-LAST:event_menuItemIniciarSesionActionPerformed

    private void menuItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCerrarSesionActionPerformed
        menuItemIniciarSesion.setVisible(true);
        menuItemAbrirCurso.setVisible(false);
        menuItemCerrarSesion.setVisible(false);

        menuItemRegistrarDocente.setVisible(false);
        menuItemRegistrarAlumno.setVisible(false);
        menuItemCrearActividad.setVisible(false);
    }//GEN-LAST:event_menuItemCerrarSesionActionPerformed

    private void menuItemAbrirCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAbrirCursoActionPerformed
        desktopPane.add(ventanaAbrirCurso);
        ventanaAbrirCurso.setVisible(true);
    }//GEN-LAST:event_menuItemAbrirCursoActionPerformed

    private void menuItemRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistrarAlumnoActionPerformed
        desktopPane.add(ventanaRegistraEstudiante);
        ventanaRegistraEstudiante.setVisible(true);
    }//GEN-LAST:event_menuItemRegistrarAlumnoActionPerformed

    private void menuItemRegistrarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistrarDocenteActionPerformed
        desktopPane.add(ventanaRegistarDocente);
        ventanaRegistarDocente.setVisible(true);
    }//GEN-LAST:event_menuItemRegistrarDocenteActionPerformed

    private void menuItemCrearActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearActividadActionPerformed
        desktopPane.add(ventanaGestionActividades);
        ventanaGestionActividades.setVisible(true);
    }//GEN-LAST:event_menuItemCrearActividadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemAbrirCurso;
    private javax.swing.JMenuItem menuItemCerrarSesion;
    private javax.swing.JMenuItem menuItemCrearActividad;
    private javax.swing.JMenuItem menuItemIniciarSesion;
    private javax.swing.JMenuItem menuItemRegistrarAlumno;
    private javax.swing.JMenuItem menuItemRegistrarDocente;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
